# Generated by Django 4.1.1 on 2022-09-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=100)),
                ('prazo', models.CharField(max_length=10)),
            ],
        ),
    ]
